### ISSUE TITLE
Is there examples somewhere

### ISSUE THREAD

**Issue by patcmorneau** [stack-of-tasks/eigenpy#397]
So i installed eigenpy with pip and this is how far i could get.
```python
from eigenpy import eigenpy_pywrap as eigenpy
from inspect import getmembers, isfunction

functions_list = getmembers(eigenpy)
#print(functions_list)

V = eigenpy.StdVec_VectorXd(1)
```

the last line gives me the error :
```python
V = eigenpy.StdVec_VectorXd(1)
Boost.Python.ArgumentError: Python argument types in
    StdVec_VectorXd.__init__(StdVec_VectorXd, int)
did not match C++ signature:
    __init__(_object* self, std::vector<Eigen::Matrix<double, -1, 1, 0, -1, 1>, Eigen::aligned_allocator<Eigen::Matrix<double, -1, 1, 0, -1, 1> > > other)
    __init__(_object* self, unsigned long size, Eigen::Matrix<double, -1, 1, 0, -1, 1> value)
    __init__(_object*)
```

I wanted to verify what i was doing with eigen in c++ with simplier scenario in python with numpy... but i guess i will stick to c++.

anyway, keep up the good work and if you have any suggestion, feel free to share

**Comment by nim65s** [comment]
Hi @patcmorneau,

I don't think I understand what you are trying to achieve.

eigenpy provide ways to efficiently bind your C++ / Eigen code into Python / Numpy scripts. 

eigenpy is not intended to be used on its own, like what your snippet suggest. You need to write C++ code, and create a Boost::Python module of it with eigenpy, so that you can call use your C++ code more easily from Python.

To answer to your title, yes, there are plenty of examples in the [unittest](https://github.com/stack-of-tasks/eigenpy/blob/master/unittest) directory, eg:
- https://github.com/stack-of-tasks/eigenpy/blob/master/unittest/geometry.cpp
- used in https://github.com/stack-of-tasks/eigenpy/blob/master/unittest/python/test_geometry.py

In other projects C++ projects with python bindings:
- https://github.com/stack-of-tasks/pinocchio/blob/master/bindings/python/module.cpp
- https://github.com/humanoid-path-planner/hpp-fcl/blob/devel/python/fcl.cc
- https://github.com/ros-planning/moveit/blob/master/moveit_ros/planning_interface/move_group_interface/src/wrap_python_move_group.cpp

**Comment by patcmorneau** [comment]
thank you, definitely not was i looking for
