### ISSUE TITLE
Failing to detect scipy even being installed

### ISSUE THREAD

**Issue by miquelmassot** [stack-of-tasks/eigenpy#469]
Part of a CI pipeline, I am installing numpy and scipy, then EigenPy. The pipeline fails at finding scipy just after having installed it.

https://github.com/miquelmassot/g2o-python/actions/runs/9020024667/job/24784257118#step:4:160

**Comment by nim65s** [comment]
Hi @miquelmassot,

I'm currently working on this. Can you try https://github.com/cmake-wheel/eigenpy/commit/11897d25a9d66ec082d63075b689b91cd449e29d on your side ?

**Comment by nim65s** [comment]
Hum, no, you are not explicitly trying to build eigenpy, so you should use binaries. So I guess the best option is to wait a bit for me to release a package with the fix, sorry for that.

**Comment by miquelmassot** [comment]
Thanks for looking into this @nim65s !
Just to clarify:
 - Wheels are not available for EigenPy, just source tarballs.
 - `pip install numpy scipy && pip install EigenPy` fails in the above CI pipeline.

**Comment by nim65s** [comment]
> Wheels are not available for EigenPy, just source tarballs.

Could you elaborate on that ? I see plenty of wheels at https://pypi.org/project/eigenpy/#files

> `pip install numpy scipy && pip install EigenPy` fails in the above CI pipeline.

This is expected. The first command change nothing for the second, as pip by default, pip builds stuff in isolated mode. It basically create a venv for the build, and install build dependencies there, no matter what you have on your computer. Therefore, the fix is to add scipy in the build dependency list on the package itself, which is what https://github.com/cmake-wheel/eigenpy/commit/11897d25a9d66ec082d63075b689b91cd449e29d is doing.

**Comment by miquelmassot** [comment]
I was wrong - I've edited my comment above.
For the 2nd point - I will wait for a release with that fix, thanks!

**Comment by nim65s** [comment]
Oh, thanks. macos arm64 wheels build failed, and once again I didn't notice. Thanks a lot for the details !

https://cirrus-ci.com/task/5781938814844928?logs=install_cibuildwheel#L1 I'll fix this, it should be pretty fast.

**Comment by nim65s** [comment]
@miquelmassot : macosx_11_0_arm64 wheels are now available on https://pypi.org/project/eigenpy/#files. Could you check if this fix your CI, and close this thread accordingly ?

**Comment by miquelmassot** [comment]
Brilliant! thanks @nim65s
