### ISSUE TITLE
Timeline for sharing memory between Eigen and NumPy

### ISSUE THREAD

**Issue by jcarpent** [stack-of-tasks/eigenpy#88]
I've implemented the complete share of memory between Eigen and Numpy without requiring any memory copy or allocation. I will suggest it as PR soon.

In the meantime, we need to decide in a similar way as #87 when to achieve the official switch.

**Comment by gabrielebndn** [comment]
Hallo! News about this?

**Comment by gabrielebndn** [comment]
Why is a timeline needed? What would the problem be if we integrated it right now? I do not think any existing Python code would be broken or would modify its behavior if this change is integrated

**Comment by jcarpent** [comment]
Yes, it will. Because when you write something like:
```
R = data.oMi[joint_id]
R[0,0] = 2.
```
it will mean the memory will change also in data.

**Comment by gabrielebndn** [comment]
> Yes, it will. Because when you write something like:
> 
> ```
> R = data.oMi[joint_id]
> R[0,0] = 2.
> ```
> 
> it will mean the memory will change also in data. And a lot of people are doing this kind of stuff!

I see. But I think that mostly concerns Pinocchio, not eigenpy. The point is, in order to make it work, we are forced to *explicitly* write in our bindings that we want a copy to be made. That is what is being done in Pinocchio. So, if you do include this change in eigenpy, then it will be a matter for Pinocchio to make the switch so to make productive use of this new possibility.
Am I wrong?

**Comment by jcarpent** [comment]
No, but you might be aware that currently, I do not have so much to perform both transistions on EigenPy and Pinocchio.

**Comment by gabrielebndn** [comment]
> No, but you might be aware that currently, I do not have so much to perform both transistions on EigenPy and Pinocchio.

You do not have so much time, you mean?
Maybe you can do it just on eigenpy, so that we can use the new feature in things like hpp-fcl and curves. What other libraries are using eigenpy?

**Comment by jcarpent** [comment]
Yes, I do not have time right now.

**Comment by jcarpent** [comment]
I will try this week, but I'm not sure I will be able to make it.

**Comment by jcarpent** [comment]
By the way, this missing feature should not block you on making bindings for hpp-fcl and others.

**Comment by gabrielebndn** [comment]
> By the way, this missing feature should not block you on making bindings for hpp-fcl and others.

It does not ;) Itś just that I stumbled into this while working on it and I thought it would be nice to solve the problem once and for all

**Comment by jcarpent** [comment]
Yes, I do agree. But, you know, a lot of things missing are mainly a matter of time.

**Comment by cmastalli** [comment]
It would definitely important for Crocoddyl. It would great if we can find a fast solution that doesn't affect Pinocchio users, and we can soon integrate to Crocoddyl.

On the other hand, it should be ok that this operation changes the memory, this is what everyone expect. If someone has such kind of Python code then it's wrong and but practice. We shouldn't matter this, otherwise the user should make a copy of the rotation matrix. Why do we need to care about wrong code?

**Comment by wxmerkt** [comment]
I am all for the change and pybind11 supported it from the get-go.

However:

> Why should we care of wrong practice?

Because it breaks existing code "silently" (and good luck tracking those bugs down if you do not follow the eigenpy repository and all related discussions and the update comes with an apt-get....) that followed the existing convention (without `.copy()`) and worked just fine. To be clear: I don't have any code that may break but this kind of change can easily throw users into debugging hell.

**Comment by cmastalli** [comment]
I understand but we shouldn't be constrained by Pinocchio. This is an independent project with its own personality

**Comment by duburcqa** [comment]
@jcarpent I have a access to your implementation ? I have done the same and I would like to benchmark it.

**Comment by jcarpent** [comment]
@duburcqa I have no time to share it now. Sorry. I can give a look at your implementation ;)

**Comment by gabrielebndn** [comment]
@jcarpent or, you could release eigenpy 3 ;) I think this feature is important and the sooner it is merged, the better

**Comment by jcarpent** [comment]
@gabrielebndn I don't know how to say that, but I'm feeling a bit alone to support both Pinocchio and EigenPy, and so many other stuff! It is very easy to ask new features, but much harder to implement them, with the underlying support.

**Comment by gabrielebndn** [comment]
@jcarpent I had understood that the feature was already implemented, and that it was only a question of when and how so not to disrupt anybody else's work. If this is not the case, I was wrong. If instead the work is ready, I think users can only welcome the new feature and it will be up to them to make their own code compatible, assuming they have been properly warned.

Of course I did not mean to be pushy, it was just a half-joking way to inquire on the status of the issue. I totally understand you are undertaking a massive job and we are all grateful about it.

Anyhow, if you feel lonely in your work, it would certainly help to disclose what you have made on a beta branch and let people play with it, other than sharing what problems you still encounter and what is preventing you from releasing it. Just a suggestion

**Comment by gabrielebndn** [comment]
@jcarpent, for instance, I imagine that lots of unit tests in Gepetto code base will have to be revisited, those of Pinocchio in particular. With a beta release of the new eigenpy, we could work about it in advance.

**Comment by jcarpent** [comment]
#163 and #160 did the job and are now available in the version 2.1.0.
